views:
  - output: "index.html"
    query: "venues.rq"
    template: "venue_index.html"
  - output: "venues.html"
    query: "venues.rq"
    template: "venue_index.html"
  - output: "{{qid}}.html"
    query: "venues.rq"
    template: "venue.html"
  - output: "map.json"
    query: "venues-with-coords.rq"
    template: "pages/map.json"
  - output: "map.html"
    template: "map.html"
  - output: "links.html"
    template: "links.html"
  - output: "posts.html"
    template: "posts.html"
  - output: "2023-06-17_atwoods.html"
    template: "posts/2023-06-17_atwoods.html"
