views:
  - output: "index.html"
    query: "venues.rq"
    template: "venue_index.html"
  - output: "venues.html"
    query: "venues.rq"
    template: "venue_index.html"
  - output: "{{qid}}.html"
    query: "venues.rq"
    template: "venue.html"
  - output: "links.html"
    template: "links.html"
